'use strict';

var category = {
    "male": {
        "id": "category-male-id",
        "name": "男生",
        "category": [{
            "name": "玄幻",
            "bookCount": 464463
        }, {
            "name": "奇幻",
            "bookCount": 43797
        }, {
            "name": "武侠",
            "bookCount": 38232
        }, {
            "name": "仙侠",
            "bookCount": 123049
        }, {
            "name": "都市",
            "bookCount": 326468
        }, {
            "name": "职场",
            "bookCount": 14870
        }, {
            "name": "历史",
            "bookCount": 65249
        }, {
            "name": "军事",
            "bookCount": 14086
        }, {
            "name": "游戏",
            "bookCount": 76058
        }, {
            "name": "竞技",
            "bookCount": 5358
        }, {
            "name": "科幻",
            "bookCount": 105109
        }, {
            "name": "灵异",
            "bookCount": 31104
        }, {
            "name": "同人",
            "bookCount": 36176
        }, {
            "name": "轻小说",
            "bookCount": 4669
        }]
    },
    "female": {
        "id": "category-female-id",
        "name": "女生",
        "category": [{
            "name": "古代言情",
            "bookCount": 394675
        }, {
            "name": "现代言情",
            "bookCount": 496093
        }, {
            "name": "青春校园",
            "bookCount": 105017
        }, {
            "name": "纯爱",
            "bookCount": 123363
        }, {
            "name": "玄幻奇幻",
            "bookCount": 119338

        }, {
            "name": "武侠仙侠",
            "bookCount": 60737
        }, {
            "name": "科幻",
            "bookCount": 8728
        }, {
            "name": "游戏竞技",
            "bookCount": 5730
        }, {
            "name": "悬疑灵异",
            "bookCount": 13062
        }, {
            "name": "同人",
            "bookCount": 122280
        }, {
            "name": "女尊",
            "bookCount": 19896
        }, {
            "name": "莉莉",
            "bookCount": 24202
        }]
    },
    "press": {
        "id": "category-press-id",
        "name": "出版",
        "category": [{
            "name": "传记名著",
            "bookCount": 2737
        }, {
            "name": "出版小说",
            "bookCount": 5372
        }, {
            "name": "人文社科",
            "bookCount": 14720
        }, {
            "name": "生活时尚",
            "bookCount": 1244
        }, {
            "name": "经管理财",
            "bookCount": 4697
        }, {
            "name": "外文原版",
            "bookCount": 684
        }, {
            "name": "青春言情",
            "bookCount": 3649
        }, {
            "name": "政治军事",
            "bookCount": 311
        }, {
            "name": "成功励志",
            "bookCount": 5527
        }, {
            "name": "育儿健康",
            "bookCount": 4794
        }]
    }
};

export default category;